apiVersion: v1
kind: Secret
metadata:
  name: {{ include "insurance-chat-assistant.secretName" . }}
  labels:
    {{- include "insurance-chat-assistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  LLM_API_KEY: {{ .Values.env.llmApiKey | quote }}
  EMBED_API_KEY: {{ .Values.env.embedApiKey | quote }}
  RAIL_API_KEY: {{ .Values.env.railApiKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "insurance-chat-assistant.postgresSecretName" . }}
  labels:
    {{- include "insurance-chat-assistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.env.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.env.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.env.postgresPassword | quote }}
  POSTGRES_URI: {{ printf "postgresql://%s:%s@%s-postgres:5432/%s" .Values.env.postgresUser .Values.env.postgresPassword (include "insurance-chat-assistant.fullname" .) .Values.env.postgresDb | quote }}