apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "insurance-chat-assistant.fullname" . }}-advisor-config
  labels:
    {{- include "insurance-chat-assistant.labels" . | nindent 4 }}
data:
  TEXT_EMBED_PORT: {{ .Values.advisorConfig.textEmbedPort | quote }}
  TEXT_MODEL_NAME: {{ .Values.advisorConfig.textModelName | quote }}
  IMAGE_EMBED_PORT: {{ .Values.advisorConfig.imageEmbedPort | quote }}
  IMAGE_MODEL_NAME: {{ .Values.advisorConfig.imageModelName | quote }}
  DB_PORT: {{ .Values.advisorConfig.dbPort | quote }}
  DB_NAME: {{ .Values.advisorConfig.dbName | quote }}
  SIM_THRESHOLD: {{ .Values.advisorConfig.simThreshold | quote }}
  TEXT_COLLECTION: {{ .Values.advisorConfig.textCollection | quote }}
  IMAGE_COLLECTION: {{ .Values.advisorConfig.imageCollection | quote }}
  DATA_SOURCE: {{ .Values.advisorConfig.dataSource | quote }}
